# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'RCBB' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RCBB
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  target 'RCBBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RCBBUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
